/planning/motion_planning/obstacle_trajectory_time: 8.0
/planning/motion_planning/delta_t: 0.1
/planning/motion_planning/reference_smoother_deviation_weight: 10.0
/planning/motion_planning/reference_smoother_curvature_weight: 4.0
/planning/motion_planning/reference_smoother_heading_weight: 10.0
/planning/motion_planning/reference_smoother_distance_weight: 5.0
/planning/motion_planning/reference_smoother_max_curvature: 100
/planning/motion_planning/spline_order: 5
/planning/motion_planning/max_lookahead_time: 8.0
/planning/motion_planning/min_lookahead_time: 1.0
/planning/motion_planning/lon_safety_buffer: 3.0
/planning/motion_planning/lat_safety_buffer: 1.0
/planning/motion_planning/max_lookahead_distance: 100.0
/planning/motion_planning/max_lookback_distance: 30.0
/planning/motion_planning/reference_max_forward_distance: 200.0
/planning/motion_planning/reference_max_backward_distance: 30.0
/planning/motion_planning/max_lon_acc: 2.0
/planning/motion_planning/min_lon_acc: -2.0
/planning/motion_planning/max_lon_velocity: 10.0
/planning/motion_planning/min_lon_velocity: 0.0
/planning/motion_planning/max_lon_jerk: 5.0
/planning/motion_planning/min_lon_jerk: -5.0
/planning/motion_planning/target_speed: 8.333
/planning/motion_planning/maneuver_forward_clear_threshold: 20.0
/planning/motion_planning/maneuver_backward_clear_threshold: 10.0
/planning/motion_planning/maneuver_target_lane_forward_clear_distance: 20.0
/planning/motion_planning/maneuver_target_lane_backward_clear_distance: 15.0
/planning/motion_planning/min_lookahead_distance: 1.0
/planning/motion_planning/maneuver_change_lane_speed_discount_factor: 0.6
/planning/motion_planning/maneuver_execute_time_length: 8.0
/planning/motion_planning/maneuver_safety_cost_gain: 10.0
/planning/motion_planning/maneuver_efficiency_cost_gain: 6.0
/planning/motion_planning/maneuver_comfort_cost_gain: 5.0
/planning/motion_planning/lattice_weight_opposite_side_offset: 10.0
/planning/motion_planning/lattice_weight_same_side_offset: 5.0
/planning/motion_planning/lattice_weight_dist_travelled: 15.0
/planning/motion_planning/lattice_weight_target_speed: 12.0
/planning/motion_planning/lattice_weight_collision: 20
/planning/motion_planning/lattice_weight_lon_jerk: 10.0
/planning/motion_planning/lattice_weight_lon_target: 20.0
/planning/motion_planning/lattice_weight_lat_offset: 20.0
/planning/motion_planning/lattice_weight_lat_jerk: 30
